app = "devflow-console-server"


[build]
dockerfile = "Dockerfile"


[env]
PORT = "5000"
FRONTEND_URL = "https://devflow-console.vercel.app/"


[http_service]
internal_port = 5_000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1


[[services.ports]]
handlers = [ "http" ]
port = 80


[[services.ports]]
handlers = [ "tls", "http" ]
port = 443
